---
  - block:

      - name: Kong | Check if package is installed
        command: dpkg-query -W kong
        register: kong_check_deb
        become: yes
        failed_when: kong_check_deb.rc > 1
        changed_when: kong_check_deb.rc == 1
        tags:
          -kong

      - name: Kong | download package
        get_url:
          url="https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists/kong-community-edition-{{kong_version}}.{{ansible_distribution_release}}.all.deb"
          dest="/tmp/kong.deb"
        when: kong_check_deb.rc == 1
        tags:
          -kong


      - name: Kong | install package
        apt: deb="/tmp/kong.deb"
        become: true
        when: kong_check_deb.rc == 1
        tags:
          -kong

    when: ansible_os_family == "Debian"

  - block:

      - name: Kong | Check if package is installed
        command: rpm -q kong
        register: kong_check_rpm
        become: yes
        failed_when: kong_check_rpm.rc > 1
        changed_when: kong_check_rpm.rc == 1
        tags:
          -kong

      - name: Kong | download package
        get_url:
          url="https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=dists/kong-community-edition-{{kong_version}}.el{{ansible_distribution_version}}.noarch.rpm"
          dest="/tmp/kong.rpm"
        when: kong_check_rpm.rc == 1
        tags:
          -kong


      - name: Kong | install package
        yum:
          name: /tmp/kong.rpm
          state: present
        become: true
        when: kong_check_rpm.rc == 1
        tags:
          -kong

    when: ansible_os_family == "CentOS"

  - block:

      - name: Kong | Check if package is installed
        command: rpm -q kong
        register: kong_check_rpm
        become: yes
        failed_when: kong_check_rpm.rc > 1
        changed_when: kong_check_rpm.rc == 1
        tags:
          -kong

      - name: Kong | download package
        get_url:
          url="https://bintray.com/kong/kong-community-edition-rpm"
          dest="/tmp/kong.rpm"
        when: kong_check_rpm.rc == 1
        tags:
          -kong


      - name: Kong | install package
        yum:
          name: /tmp/kong.rpm
          state: present
        become: true
        when: kong_check_rpm.rc == 1
        tags:
          -kong

    when: ansible_os_family == "Fedora"
