---
- hosts: www
  gather_facts: False

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python if absent
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      apt: pkg="acl"
      become: yes

    - name: gather facts
      setup:

  roles:
     - {
         role: "sa-kong"
       }


  tasks:

    - debug: msg="Tasks section"
